#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("acs.Demo.Resource", IsApplication=true)]

namespace acs.Demo
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050001
			public const int display_lcd_message_dialog_edit_text_message = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int display_lcd_message_dialog_scroll_view = 2131034112;
			
			// aapt resource value: 0x7f050007
			public const int main_button_close = 2131034119;
			
			// aapt resource value: 0x7f050013
			public const int main_button_control = 2131034131;
			
			// aapt resource value: 0x7f050019
			public const int main_button_display_lcd_message = 2131034137;
			
			// aapt resource value: 0x7f05000c
			public const int main_button_get_atr = 2131034124;
			
			// aapt resource value: 0x7f050015
			public const int main_button_get_features = 2131034133;
			
			// aapt resource value: 0x7f050012
			public const int main_button_get_id = 2131034130;
			
			// aapt resource value: 0x7f050010
			public const int main_button_get_protocol = 2131034128;
			
			// aapt resource value: 0x7f050009
			public const int main_button_get_state = 2131034121;
			
			// aapt resource value: 0x7f050005
			public const int main_button_list = 2131034117;
			
			// aapt resource value: 0x7f050017
			public const int main_button_modify_pin = 2131034135;
			
			// aapt resource value: 0x7f050006
			public const int main_button_open = 2131034118;
			
			// aapt resource value: 0x7f05000b
			public const int main_button_power = 2131034123;
			
			// aapt resource value: 0x7f050018
			public const int main_button_read_key = 2131034136;
			
			// aapt resource value: 0x7f05000f
			public const int main_button_set_protocol = 2131034127;
			
			// aapt resource value: 0x7f050011
			public const int main_button_transmit = 2131034129;
			
			// aapt resource value: 0x7f050016
			public const int main_button_verify_pin = 2131034134;
			
			// aapt resource value: 0x7f05000d
			public const int main_check_box_t0 = 2131034125;
			
			// aapt resource value: 0x7f05000e
			public const int main_check_box_t1 = 2131034126;
			
			// aapt resource value: 0x7f050003
			public const int main_edit_text_command = 2131034115;
			
			// aapt resource value: 0x7f050014
			public const int main_edit_text_control = 2131034132;
			
			// aapt resource value: 0x7f05000a
			public const int main_spinner_power = 2131034122;
			
			// aapt resource value: 0x7f050004
			public const int main_spinner_reader = 2131034116;
			
			// aapt resource value: 0x7f050008
			public const int main_spinner_slot = 2131034120;
			
			// aapt resource value: 0x7f050002
			public const int main_text_view_response = 2131034114;
			
			// aapt resource value: 0x7f050023
			public const int modify_pin_dialog_edit_text_confirm_pin = 2131034147;
			
			// aapt resource value: 0x7f05002b
			public const int modify_pin_dialog_edit_text_data = 2131034155;
			
			// aapt resource value: 0x7f050024
			public const int modify_pin_dialog_edit_text_entry_validation_condition = 2131034148;
			
			// aapt resource value: 0x7f05001d
			public const int modify_pin_dialog_edit_text_format_string = 2131034141;
			
			// aapt resource value: 0x7f050021
			public const int modify_pin_dialog_edit_text_insertion_offset_new = 2131034145;
			
			// aapt resource value: 0x7f050020
			public const int modify_pin_dialog_edit_text_insertion_offset_old = 2131034144;
			
			// aapt resource value: 0x7f050026
			public const int modify_pin_dialog_edit_text_lang_id = 2131034150;
			
			// aapt resource value: 0x7f050027
			public const int modify_pin_dialog_edit_text_msg_index1 = 2131034151;
			
			// aapt resource value: 0x7f050028
			public const int modify_pin_dialog_edit_text_msg_index2 = 2131034152;
			
			// aapt resource value: 0x7f050029
			public const int modify_pin_dialog_edit_text_msg_index3 = 2131034153;
			
			// aapt resource value: 0x7f050025
			public const int modify_pin_dialog_edit_text_number_message = 2131034149;
			
			// aapt resource value: 0x7f05001e
			public const int modify_pin_dialog_edit_text_pin_block_string = 2131034142;
			
			// aapt resource value: 0x7f05001f
			public const int modify_pin_dialog_edit_text_pin_length_format = 2131034143;
			
			// aapt resource value: 0x7f050022
			public const int modify_pin_dialog_edit_text_pin_max_extra_digit = 2131034146;
			
			// aapt resource value: 0x7f05002a
			public const int modify_pin_dialog_edit_text_teo_prologue = 2131034154;
			
			// aapt resource value: 0x7f05001b
			public const int modify_pin_dialog_edit_text_timeout = 2131034139;
			
			// aapt resource value: 0x7f05001c
			public const int modify_pin_dialog_edit_text_timeout2 = 2131034140;
			
			// aapt resource value: 0x7f05001a
			public const int modify_pin_dialog_scroll_view = 2131034138;
			
			// aapt resource value: 0x7f050031
			public const int read_key_dialog_edit_text_echo_lcd_mode = 2131034161;
			
			// aapt resource value: 0x7f050030
			public const int read_key_dialog_edit_text_echo_lcd_start_position = 2131034160;
			
			// aapt resource value: 0x7f05002f
			public const int read_key_dialog_edit_text_key_return_condition = 2131034159;
			
			// aapt resource value: 0x7f05002e
			public const int read_key_dialog_edit_text_pin_max_extra_digit = 2131034158;
			
			// aapt resource value: 0x7f05002d
			public const int read_key_dialog_edit_text_timeout = 2131034157;
			
			// aapt resource value: 0x7f05002c
			public const int read_key_dialog_scroll_view = 2131034156;
			
			// aapt resource value: 0x7f05003e
			public const int verify_pin_dialog_edit_text_data = 2131034174;
			
			// aapt resource value: 0x7f050039
			public const int verify_pin_dialog_edit_text_entry_validation_condition = 2131034169;
			
			// aapt resource value: 0x7f050035
			public const int verify_pin_dialog_edit_text_format_string = 2131034165;
			
			// aapt resource value: 0x7f05003b
			public const int verify_pin_dialog_edit_text_lang_id = 2131034171;
			
			// aapt resource value: 0x7f05003c
			public const int verify_pin_dialog_edit_text_msg_index = 2131034172;
			
			// aapt resource value: 0x7f05003a
			public const int verify_pin_dialog_edit_text_number_message = 2131034170;
			
			// aapt resource value: 0x7f050036
			public const int verify_pin_dialog_edit_text_pin_block_string = 2131034166;
			
			// aapt resource value: 0x7f050037
			public const int verify_pin_dialog_edit_text_pin_length_format = 2131034167;
			
			// aapt resource value: 0x7f050038
			public const int verify_pin_dialog_edit_text_pin_max_extra_digit = 2131034168;
			
			// aapt resource value: 0x7f05003d
			public const int verify_pin_dialog_edit_text_teo_prologue = 2131034173;
			
			// aapt resource value: 0x7f050033
			public const int verify_pin_dialog_edit_text_timeout = 2131034163;
			
			// aapt resource value: 0x7f050034
			public const int verify_pin_dialog_edit_text_timeout2 = 2131034164;
			
			// aapt resource value: 0x7f050032
			public const int verify_pin_dialog_scroll_view = 2131034162;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int display_lcd_message_dialog = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int foo = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int modify_pin_dialog = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int read_key_dialog = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int verify_pin_dialog = 2130903045;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
